# Generated by Django 3.2.5 on 2022-04-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email_user',
            field=models.CharField(default='corre@hotmail.com', max_length=300),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(default='no llenado', max_length=200),
        ),
    ]
